- scripts/rpm/postInstall.sh
We initialize the db in the rpm post install which runs as root however
the db should be owned by the werbserver
Ideally I'd su apache -c ... this but apache user is locked so this is
2nd best option
> ASM-2835: Fix perms of graphite DB

- build.gradle
Equallogic module was recently changed to create the
/opt/Dell/ASM/cache directory if it didn't exist. SCVMM module also
uses that directory and when equallogic ran first (as user root) it
created the directory in such a way that the SCVMM directory could no
longer write there.
> ASM-4063 add cache directory to deployer rpm

- build.gradle
Used 1777 previously which was interpreted as decimal. Had to prefix
with 0 to make it octal.
> ASM-4063 fix /opt/Dell/ASM/cache permissions

- build.gradle
Queued inventory and puppet_apply jobs will have output files stored
under /opt/Dell/ASM/jobs/[CERTNAME]
> ASM-4070 add asm-deployer jobs output directory

- build.gradle
- scripts/rpm/postInstall.sh
This adds a logrotate config file for the graphite logs as well as
disable some logging settings in the config
carbon-cache was logging a lot about missing storage-aggregation.conf
which we don't use so this also just touches the file
> ASM-4473: Add logrotation and disable more logging

- scripts/rpm/postInstall.sh
This is for backwards compatability if the appliance was created with
the wrong permissions on the Gemfile.lock, we will be unable to install
any added Gem dependencies added to the Gemfile.
> Change Gemfile.lock permissions

- scripts/rpm/postInstall.sh
This was caused by an ordering issue on the asm-deployer postinstall
that was causing the graphite syncdb task to not run
> ASM-4515  UI doesn't redirect correctly

- build.gradle
The asm-deployer Gemfile has to depend on the git version of the
dell-asm-util gem so that Travis CI tests can run with the latest
version of that code. However, the appliance needs to use the version
of dell-asm-util that is included in the appliance Dell-ASM-Gems
rpm. Modify the asm-deployer rpm gradle build to simply remove the
:git tag from the dell-asm-util dependency so that the installed
dell-asm-util gem will be used.
> ASM-4913 ensure rpm gem updates used by asm-deployer

- build.gradle
Now handled entirely by Dell-ASM-razor-server-repo-store. This was needed because the generated and static ISOs are now served from the appliance CIFs share that is generally controlled by the Dell-ASM-razor-repo-store rpm.
> ASM-5589 Remove /var/nfs from asm-deployer rpm

- build.gradle
Some new scripts such as capture_deployment_for_jira.sh were not
executable.
> misc: make asm-deployer scripts executable

- build.gradle
Execute permission was missing from the ruby script used for identifying the OS version of the VM. As a result VM post-installation of clone VM was getting skipped.
> ASM-6162 Hyperv VM post-installation failing

- scripts/rpm/postInstall.sh
This changes the max nagios concurrent nagios checks from unlimited to
4, this will have an impact on how quickly issues are detected on
hardware especially on setups with many resources but it wont consume
all the resources anymore
If there is docs about setting up a split nagios / deployer scenario we
should mention that the max_concurrent_checks should be set back to 0 if
there is a dedicated nagios worker node
> ASM-8346 limit maximum nagios checks to 4

- scripts/rpm/postInstall.sh
This reverts commit 438bad0689868955f4fcb364e3ee3e5d40c7f7e2.
The effect of this combined with the pattern in use by the load short
circuit service has the effect that the load short circuit checks are
skipped under load - and so the short circuit pattern is often not
effective
After discussion we felt the short circuit is going to be a better long
term way to combat the load problems - at the cost of short spikes where
many checks will be called when the node crosses the threshold of low
load to high load
> Revert "ASM-8346 limit maximum nagios checks to 4"

- build.gradle
- scripts/rpm/postInstall.sh
This used to be done in Dell-ASM-Gems, but it is more approriate
here. This rpm already has a dependency on Dell-ASM-Gems so that it
gets upgraded first. This way "bundle update --local" will be run
after the new gems are installed and after the asm-deployer Gemfile
has been updated to match.
Also removed the sed of Gemfile.lock since "bundle update --local"
will do it.
> ASM-8606 Run "bundle update --local" from post-install script

- build.gradle
- files/Gemfile.lock
- scripts/rpm/postInstall.sh
Previously the Gemfile.lock was not included in the asm-deployer
rpm. "bundle update --local" was run as a postinstall script in order
to generate it based on what gems were installed on the
appliance. That makes it very difficult to determine what gems are
_supposed_ to be included on the appliance.
This commit adds the Gemfile.lock to the rpm and removes the "bundle
update --local" post-install. Also tightens up permissions on
/opt/asm-deployer since we no longer expect torquebox to write into
that directory.
> [misc] Add Gemfile.lock for asm-deployer

- build.gradle
The ASM Installation Guide documents the process for preparing VM
clone images for use in ASM deployments. Part of that process
involves copying script files from the ASM appliance and
downloading ruby gems from the internet. This change consolidates
all the needed files into a single location on the appliance
accessible via its CIFS share.
> ASM-6900 Create files for easy VM Cloning

- files/Gemfile.lock
I revved the rubocop version recently in asm-deployer. That was
intended to be a dev-only change but since all gems are included on
the appliance gem updates will fail if the same change isn't included
in the gems rpm and the asm-deployer Gemfile.lock.
> [misc] Update rubocop gem

- build.gradle
These are the changes to Artifactory to support ASM-9477.
A Nagios plugin to monitor appliance disk space.  It'll
monitor all partitions if this is an issue, we'll only
monitor /var.  The plugin and service will return percent
used.  The UI will determine if an alert is triggered
> ASM-9675 Update RPMs required for disk space monitoring

- build.gradle
In general all Redline `Builder.addFile(...)` or
`Builder.addDirectory(...)` calls need to set the `addParents` boolean
to false. It unhelpfully defaults to true. When set to false it claims
ownership of all parent directories in addition to the actual path
specified. Yum in CentOS 7 will refuse to install RPMs that claim to
own the same directory as another RPM.
> [maint] RPM fixes in preparation for CentOS 7

- build.gradle
The rpm no longer exists in the EPEL CentOS 7 repository.
> [maint] graphite-web-selinux not needed for CentOS 7

- files/Gemfile.lock
net-scp is required in order to copy files to the ScaleIO Gateway VM
via SCP.
> LUD-221 Add net-scp to asm-deployer Gemfile.lock

- files/Gemfile.lock
Seeing heap space failures when executing
`ASM::WsMan#idrac_card_enumeration` with all of the java nokogiri
1.8.x gems. Issue does not exist in the 1.7 series.
> LUD-513 Downgrade to nokogiri 1.7.2-java due to memory issues

- build.gradle
Changed ownership in build.gradle for rpmBuilder from root:razor
to razor:razor.
> LUD-1028 capture_deployment_for_jira.sh fails with permission issue

- scripts/rpm/postInstall.sh
After the upgrade to CentOS 7.x the path to the graphite manage.py
file has changed. This change is necessary but not sufficient to get
graphite fully functional again. There are still problems due to httpd
running as csadmin instead of as apache.
> LUD-689 Fix initialization of graphite sqlite db

- scripts/rpm/postInstall.sh
Updating permissions for graphite-web forlder present under /var/log and /var/lib path by default.
@gavin-scott @pschami  - as discussed, running permission command out of secret key check by default.
Please review and merge.
> LUD-689 updating permissions

- files/Gemfile.lock
The exact version has to be specified in the `Gemfile.lock`
> VXFM-1642 Fix ipaddress Gemfile.lock entry

- files/Gemfile.lock
The appliance has a patched version of rbvmomi 1.12.0 now to resolve
an OVF deployment issue.
> VXFM-2344 Update rbvmomi dependency to 1.12.0

- scripts/rpm/postInstall.sh
Building a bootable floppy image requires root access in order to do a
loopback mount.
> VXFM-4518 Grant sudo access to UEFi iPXE build script

- build.gradle
Move dependency from applicationConfigureVM to asm-deployer to
match python-modules.
> VXFM-6472 ansible-cloudlink to be installed after python modules

- build.gradle
- files/Gemfile.lock
- update Gemfile.lock
- check-racadm.rb was renamed to check_racadm.rb to meet rubocop
requirements
> VXFM-6601 Upgrade Rubocop and other gems

- scripts/rpm/postInstall.sh
Adds log rotation for asm-deployer*.log files in /var/log/razor
using the same options as those for razor server except that the
max size is increased from 5M to 50M.
> VXFM-7144 sm-deployer-init.log gets very large and not rotated
